version: 0.2

phases:
  install:
    commands:
    - rm package-lock.json
    - npm install --silent --no-progress -g npm
    - npm install --silent --no-progress -g serverless
    - npm --version
  pre_build:
    commands:
    - npm install --silent --no-progress
  build:
    commands:
    - npm run-script lint
    - npm run test
    - mkdir -p target/stg
    - mkdir target/prod
    - serverless config credentials --provider aws --key AKIASSZ4LG67NCIUAX6W --secret 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 --profile awscoder --overwrite
    - serverless package --package target/stg --stage stg -v -r us-west-2 --profile awscoder
    - serverless package --package target/prod --stage prod -v -r us-west-2 --profile awscoder

artifacts:
  files:
  - target/**/*
  - serverless.yml
  - deploy.sh
