service: gimme-time

provider:
  name: aws
  profile: awscoder
  runtime: nodejs8.10
  environment:
    STAGE: ${opt:stage}

functions:
  gimmetime:
    handler: handler.gimmetime
    events:
      - http:
          path: /time
          method: get
          request:
            parameters:
              querystrings:
                tz: true
